interface EnvironmentVariables {
  CANDLES_ENDPOINT_THE_GRAPH: string
  CANDLES_ENDPOINT_PYTH: string
  MAINNET_REST_API: string
  WALLET_CONNECT_ID: string

  OSMOSIS1_REST: string
  OSMOSIS1_RPC: string
  OSMOSIS_DEVNET_REST: string
  OSMOSIS_DEVNET_RPC: string

  PION1_REST: string
  PION1_RPC: string
}

export const ENV: EnvironmentVariables = {
  CANDLES_ENDPOINT_THE_GRAPH: process.env.NEXT_PUBLIC_CANDLES_ENDPOINT_THE_GRAPH || '',
  CANDLES_ENDPOINT_PYTH: process.env.NEXT_PUBLIC_CANDLES_ENDPOINT_PYTH || '',
  MAINNET_REST_API: process.env.NEXT_PUBLIC_MAINNET_REST || '',
  WALLET_CONNECT_ID: process.env.NEXT_PUBLIC_WALLET_CONNECT_ID || '',

  OSMOSIS1_REST: process.env.NEXT_PUBLIC_OSMOSIS1_REST || '',
  OSMOSIS1_RPC: process.env.NEXT_PUBLIC_OSMOSIS1_RPC || '',
  OSMOSIS_DEVNET_REST: process.env.NEXT_PUBLIC_OSMOSIS_DEVNET_REST || '',
  OSMOSIS_DEVNET_RPC: process.env.NEXT_PUBLIC_OSMOSIS_DEVNET_RPC || '',
  PION1_REST: process.env.NEXT_PUBLIC_PION1_REST || '',
  PION1_RPC: process.env.NEXT_PUBLIC_PION1_RPC || '',
}
