export enum LocalStorageKeys {
  TRADING_PAIR_SIMPLE = 'tradingPairSimple',
  TRADING_PAIR_ADVANCED = 'tradingPairAdvanced',
  ACCOUNT_SUMMARY_TABS = 'accountSummaryTabs',
  DISPLAY_CURRENCY = 'displayCurrency',
  REDUCE_MOTION = 'reduceMotion',
  FAVORITE_ASSETS = 'favoriteAssets',
  ENABLE_AUTO_LEND_GLOBAL = 'enableAutoLendGlobal',
  AUTO_LEND_ENABLED_ACCOUNT_IDS = 'autoLendEnabledAccountIds',
  SLIPPAGE = 'slippage',
  TERMS_OF_SERVICE = 'termsOfService',
  TUTORIAL = 'tutorial',
  TRANSACTIONS = 'transactions',
  MIGRATION_BANNER = 'migrationBanner',
  HLS_INFORMATION = 'hlsInformation',
}
