export enum LocalStorageKeys {
  ACCOUNT_SUMMARY_TABS = 'accountSummaryTabs',
  PREFERRED_ASSET = 'favouriteAsset',
  DISPLAY_CURRENCY = 'displayCurrency',
  REDUCE_MOTION = 'reduceMotion',
  FAVORITE_ASSETS = 'favoriteAssets',
  LEND_ASSETS = 'lendAssets',
  AUTO_LEND_ENABLED_ACCOUNT_IDS = 'autoLendEnabledAccountIds',
  SLIPPAGE = 'slippage',
  TERMS_OF_SERVICE = 'termsOfService',
  TUTORIAL = 'tutorial',
  TRANSACTIONS = 'transactions',
  MIGRATION_BANNER = 'migrationBanner',
  HLS_INFORMATION = 'hlsInformation',
}
