import { ActionKind } from 'types/generated/mars-perps/MarsPerps.types'

export const PERPS_DEFAULT_ACTION: { action: ActionKind } = { action: 'default' }

export const PERPS_ASSETS: AstroportAsset[] = [
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/ubtc',
    symbol: 'BTC',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/BTCLogo.svg',
    description: 'Bitcoin',
    decimals: 8,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/ueth',
    symbol: 'ETH',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/ETHLogo.svg',
    description: 'Ethereum',
    decimals: 18,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/ubnb',
    symbol: 'BNB',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/BNBLogo.svg',
    description: 'Binance Coin',
    decimals: 18,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/usol',
    symbol: 'SOL',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/SOLLogo.svg',
    description: 'Solana',
    decimals: 9,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/uxrp',
    symbol: 'XRP',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/XRPLogo.svg',
    description: 'Ripple',
    decimals: 18,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/udoge',
    symbol: 'DOGE',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/DOGELogo.svg',
    description: 'Dogecoin',
    decimals: 8,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/ushiba',
    symbol: 'SHIBA',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/SHIBALogo.svg',
    description: 'Shiba Inu',
    decimals: 18,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/uavax',
    symbol: 'AVAX',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/AVAXLogo.svg',
    description: 'Avalanche',
    decimals: 18,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/utrx',
    symbol: 'TRX',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/TRXLogo.svg',
    description: 'Tron',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/uinj',
    symbol: 'INJ',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/INJLogo.svg',
    description: 'Injective',
    decimals: 18,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/udydx',
    symbol: 'DYDX',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/DYDXLogo.svg',
    description: 'DyDx Token',
    decimals: 18,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/utia',
    symbol: 'TIA',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/TIALogo.svg',
    description: 'Celestia',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'factory/neutron166t9ww3p6flv7c86376fy0r92r88t3492xxj2h/upepe',
    symbol: 'PEPE',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/PEPELogo.svg',
    description: 'Pepe Coin',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'pion-1',
    denom: 'factory/neutron1ke0vqqzyymlp5esr8gjwuzh94ysnpvj8er5hm7/UUSDC',
    symbol: 'USDC',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/MarsUSDCLogo.svg',
    description: 'Mars USDC',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
]
