import { ActionKind } from 'types/generated/mars-perps/MarsPerps.types'

export const PERPS_DEFAULT_ACTION: { action: ActionKind } = { action: 'default' }

export const PERPS_ASSETS: AstroportAsset[] = [
  {
    chainId: 'neutron-1',
    denom: 'perps/ubtc',
    symbol: 'BTC',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/BTCLogo.svg',
    description: 'Bitcoin',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/ueth',
    symbol: 'ETH',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/ETHLogo.svg',
    description: 'Ethereum',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/uatom',
    symbol: 'ATOM',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/ATOMLogo.svg',
    description: 'Cosmos',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/ubnb',
    symbol: 'BNB',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/BNBLogo.svg',
    description: 'Binance Coin',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/usol',
    symbol: 'SOL',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/SOLLogo.svg',
    description: 'Solana',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/uxrp',
    symbol: 'XRP',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/XRPLogo.svg',
    description: 'Ripple',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/udoge',
    symbol: 'DOGE',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/DOGELogo.svg',
    description: 'Dogecoin',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/ushiba',
    symbol: 'SHIBA',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/SHIBALogo.svg',
    description: 'Shiba Inu',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/uavax',
    symbol: 'AVAX',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/AVAXLogo.svg',
    description: 'Avalanche',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/utrx',
    symbol: 'TRX',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/TRXLogo.svg',
    description: 'Tron',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/uinj',
    symbol: 'INJ',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/INJLogo.svg',
    description: 'Injective',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/udydx',
    symbol: 'DYDX',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/DYDXLogo.svg',
    description: 'DyDx Token',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/utia',
    symbol: 'TIA',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/TIALogo.svg',
    description: 'Celestia',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/upepe',
    symbol: 'PEPE',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/PEPELogo.svg',
    description: 'Pepe Coin',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/usui',
    symbol: 'SUI',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/SUILogo.svg',
    description: 'Sui',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/untrn',
    symbol: 'NTRN',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/NTRNLogo.svg',
    description: 'Neutron',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/uosmo',
    symbol: 'OSMO',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/OSMOLogo.svg',
    description: 'Osmosis',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'neutron-1',
    denom: 'perps/utrump',
    symbol: 'TRUMP',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/TRUMPLogo.svg',
    description: 'Official Trump',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
  {
    chainId: 'pion-1',
    denom: 'factory/neutron1ke0vqqzyymlp5esr8gjwuzh94ysnpvj8er5hm7/UUSDC',
    symbol: 'USDC',
    icon: 'https://raw.githubusercontent.com/mars-protocol/mars-v2-frontend/refs/heads/main/src/components/common/Icons/MarsUSDCLogo.svg',
    description: 'Mars USDC',
    decimals: 6,
    priceUSD: 0,
    totalLiquidityUSD: 0,
    dayVolumeUSD: 0,
  },
]
