type Page =
  | 'trade'
  | 'perps'
  | 'borrow'
  | 'farm'
  | 'lend'
  | 'portfolio'
  | 'portfolio/{accountId}'
  | 'hls-farm'
  | 'hls-staking'
  | 'governance'
  | 'stats'
  | 'stats-farm'
  | 'stats-lend-borrow'
  | 'stats-additional'
