import type { AppProps } from "next/app";
import Head from "next/head";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.min.css";
// import { ChainInfoID } from "@cosmos-kit/types";
// import { WalletManagerProvider } from "@cosmos-kit/react";
// import { Bech32Address } from "@keplr-wallet/cosmos";
// import { MetaMaskProvider } from "metamask-react";

import "../styles/globals.css";
import Layout from "components/Layout";
import { WalletProvider } from "hooks/useWallet/context";

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Mars V2</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <WalletProvider>
        {/* <MetaMaskProvider>
        <WalletManagerProvider
          defaultChainId={ChainInfoID.Injective1}
          renderLoader={() => null}
          chainInfoOverrides={[
            {
              rpc: "https://injective-rpc.quickapi.com:443",
              rest: "https://lcd.injective.network",
              chainId: "injective-1",
              chainName: "Injective",
              bip44: {
                coinType: 60,
              },
              bech32Config: Bech32Address.defaultBech32Config("inj"),
              currencies: [
                {
                  coinDenom: "INJ",
                  coinMinimalDenom: "inj",
                  coinDecimals: 18,
                  // coinGeckoId: "injective-protocol",
                  // coinImageUrl: "/tokens/inj.svg",
                },
              ],
              feeCurrencies: [
                {
                  coinDenom: "INJ",
                  coinMinimalDenom: "inj",
                  coinDecimals: 18,
                },
              ],
              stakeCurrency: {
                coinDenom: "INJ",
                coinMinimalDenom: "inj",
                coinDecimals: 18,
              },
              gasPriceStep: {
                low: 0.0005,
                average: 0.0007,
                high: 0.0009,
              },
              features: ["stargate", "ibc-transfer", "no-legacy-stdTx", "ibc-go"],
            },
          ]}
          classNames={{
            modalContent: "!hidden",
          }}
        > */}
        <Layout>
          <Component {...pageProps} />
        </Layout>
        <ToastContainer
          autoClose={1500}
          closeButton={false}
          position="bottom-right"
          hideProgressBar
          icon={false}
          newestOnTop
          theme="colored"
        />
      </WalletProvider>
      {/* </WalletManagerProvider>
      </MetaMaskProvider> */}
    </>
  );
}

export default MyApp;
