export enum DocURL {
  ADVANCED_TRADING_URL = 'https://docs.marsprotocol.io/docs/learn/mars-v2/trade/margin',
  BORROW_LENDING_URL = 'https://docs.marsprotocol.io/docs/learn/mars-v2/borrow',
  CHANGE_LOG_URL = 'https://docs.marsprotocol.io/docs/overview/changelog',
  COOKIE_POLICY_URL = 'https://docs.marsprotocol.io/docs/overview/legal/cookie-policy',
  COUNCIL_LEAP = 'https://cosmos.leapwallet.io/chains/mars/governance',
  COUNCIL_STATION = 'https://station.terra.money/gov#PROPOSAL_STATUS_VOTING_PERIOD',
  COUNCIL_KEPLR = 'https://wallet.keplr.app/chains/mars-hub?tab=governance',
  DOCS_URL = 'https://docs.marsprotocol.io/',
  FARM_INTRO_URL = 'https://docs.marsprotocol.io/docs/learn/tutorials/farming/farming-intro',
  HLS_INTRO_URL = 'https://docs.marsprotocol.io/docs/learn/mars-v2/high-leveraged-strategies/high-leveraged-strategies-intro',
  MANAGE_ACCOUNT_URL = 'https://docs.marsprotocol.io/docs/learn/tutorials/credit-accounts/credit-accounts-intro',
  ROVER_INTRO_URL = 'https://docs.marsprotocol.io/docs/learn/mars-v2/credit-accounts',
  PRIVACY_POLICY_URL = 'https://docs.marsprotocol.io/docs/overview/legal/privacy-policy',
  TERMS_OF_SERVICE_URL = 'https://docs.marsprotocol.io/docs/overview/legal/terms-of-service',
  TRADING_INTRO_URL = 'https://docs.marsprotocol.io/docs/learn/tutorials/trading/trading-intro',
  WALLET_INTRO_URL = 'https://docs.marsprotocol.io/docs/learn/tutorials/basics/connecting-your-wallet',
  X_SHARE_URL = 'https://x.com/intent/tweet',
}
